---
- name: Pull docker image of Scientific Calculator
  hosts: all

  tasks:
    - name: Pull scientific calculator image
      docker_image:
        name: narasimhannandagudi/scientific_calculator:latest
        source: pull